# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
# Use --no-cache-dir to reduce image size
# Install dependencies including Flask and Plotly
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code and templates/static files
COPY app.py .
COPY trading_bot.py . # Keep the bot script if needed for reference or future integration
COPY templates/ templates/
COPY static/ static/

# Copy data/log files generated by the bot (assuming they exist before building)
# Alternatively, use Docker volumes to manage these persistent files.
# COPY BTC_USDT_15m_features.csv .
# COPY signals.log .
# COPY subscribers.txt . # app.py creates this if missing

# Expose the port the Flask app runs on
EXPOSE 5000

# Define environment variables for email credentials (recommended)
# You would set these when running the container, e.g., docker run -e GMAIL_SENDER='...' -e GMAIL_PASSWORD='...' your-image-name
# ENV GMAIL_SENDER="your_email@gmail.com"
# ENV GMAIL_PASSWORD="your_app_password"
# Note: The script currently uses hardcoded values, which is less secure.
# Consider modifying the script to read from environment variables as shown commented out in the script.

# Run the Flask application when the container launches
CMD ["python", "app.py"]
